### ISSUE TITLE
Cpu usage goes higher and higher

### ISSUE THREAD

**Issue by freekmurze** [yosymfony/resource-watcher#3]
I'm using your excellent package to power my [phpunit-watcher](https://github.com/spatie/phpunit-watcher) tool.

Unfortunately when leaving the watcher running for a couple of minutes, the cpu usage begins to ramp up. It starts very early on, there's about 1% more cpu usage each 2 or 3 seconds.

This is [the code that's being looped](https://github.com/spatie/phpunit-watcher/blob/9c78537/src/Watcher.php#L53-L60). If I comment that out, the cpu stays at a stable level.

Do you know what's the cause of the ramp up in cpu usage and how this can be fixed?

**Comment by colinodell** [comment]
Blackfire suggests that the `ExcludeDirectoryFilterIterator` might be the culprit here.

I created a simple test script based on your example:  https://gist.github.com/colinodell/d6fd7a4cb6d9fbf8aa20154755278385

I ran this script with 50 iterations and again with 200 - a 300% increase.  I expected to see a corresponding 300% increase in CPU usage; however, I saw a 466% increase (1.65 seconds to 9.31 seconds):

![image](https://user-images.githubusercontent.com/202034/28795560-5303916a-7608-11e7-9947-0f16e6769c04.png)

This iterator is used to exclude certain files; by default, the `Finder` will exclude dotfiles and VCS files.  On a hunch, I added these two calls to the `Finder` configuration:

```php
  ->ignoreDotFiles(false)
  ->ignoreVCS(false)
```

I then re-profiled and got these results which matched the ~300% increase I expected:

![image](https://user-images.githubusercontent.com/202034/28795641-9cc1eb26-7608-11e7-8c38-d2104f99146b.png)

CPU time went from 887ms to 3.35 seconds.

**Comment by freekmurze** [comment]
@colinodell Thank you so much for the your input here. I added

```php
  ->ignoreDotFiles(false)
  ->ignoreVCS(false)
```

and the problem seems to have been solved now. So I'm very happy with the suggestion you made.

Something I don't understand well yet is why the cpu kept growing. I'd assume that without the added code the cpu usage should have stayed on the same level. Do you know why the cpu was growing on each iteration?

**Comment by colinodell** [comment]
I'm not really sure why it kept growing.

Time spent in the constructor grew by 10x:

![image](https://user-images.githubusercontent.com/202034/28800393-762528fe-761a-11e7-9ea4-68066550a21a.png)

According to Blackfire, most of that extra time came from the constructor itself, not other function calls:

![image](https://user-images.githubusercontent.com/202034/28800519-f8888f16-761a-11e7-927b-fc2c53202d23.png)


Perhaps there's something going on at the language/interpreter level?  Maybe extra garbage collection, memory allocation, or something like that?  (I don't know - that's beyond my knowledge)

I also saw a bunch of time spent rewinding iterators - not sure if that's also related or not.

**Comment by yosymfony** [comment]
Thanks for the response @colinodell
